import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';

test('v3 pinned calculations, listening, completed judgement, hold and conflict', async ({ page, request }, testInfo) => {
  test.skip(process.env.KDOG_TEST_INTAKE_SPEC !== '20260929', 'Run with the current intake fixture.');
  test.setTimeout(90000);
  const headers = { 'X-KDOG-Request': '1' }, password = 'Browser-test-only-42';
  await request.post('/api/auth/login', { headers, data: { username: 'admin', password } });
  let item = await (await request.post('/api/cases', { headers, data: { event_id: 'V3-BASIC', participant_id: 'v3basic', dog_name: '계산 판정 합성견' } })).json();
  const media = execFileSync('ffmpeg', ['-v', 'error', '-nostdin', '-f', 'lavfi', '-i', 'testsrc=size=96x64:rate=12:duration=10', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=10', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', '-f', 'mp4', '-movflags', 'frag_keyframe+empty_moov', 'pipe:1']);
  item = await (await request.post(`/api/cases/${item.case_id}/videos`, { headers, params: { expected_revision: item.input_revision, session_id: item.selected_session_id, filename: 'synthetic-basic.mp4' }, data: media })).json();
  const base = `/api/cases/${item.case_id}/sessions/${item.selected_session_id}`, video = item.manifest.sessions[0].videos[0];
  const spans: [string, number | null, number | null][] = [['entry', 0, 1], ['baseline', 1, 2], ['alone', null, null], ['reunion', null, null], ['ignore', 2, 3], ['walk', 3.2, 4.4], ['stranger', 5, 7], ['exit', 7.2, 8.2]];
  item = await (await request.put(base + '/recording', { headers, data: { expected_revision: item.input_revision, confirm: true, recording: {
    video_id: video.video_id, segments: spans.map(([segment, start_sec, end_sec]) => ({ segment, video_id: video.video_id, start_sec, end_sec, state: start_sec === null ? 'not_performed' : 'performed', reason: start_sec === null ? '실제 분리 생략' : null })),
    walk_phases: ['move_1', 'stop_1', 'move_2', 'stop_2', 'move_3', 'stop_3'].map((phase, i) => ({ phase, video_id: video.video_id, start_sec: Number((3.2 + .2 * i).toFixed(1)), end_sec: Number((3.4 + .2 * i).toFixed(1)) })),
  } } })).json();
  const assigned = await (await request.post(base + '/sheets', { headers, data: { expected_revision: item.input_revision, assigned_username: 'reviewer', rater_id: 'basic-expert', rater_name: '기본 계산 전문가' } })).json();
  await page.goto('/');
  await page.getByLabel('계정', { exact: true }).fill('reviewer');
  await page.getByLabel('비밀번호', { exact: true }).fill(password);
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('button', { name: '로그아웃', exact: true })).toBeEnabled();
  const observations = [['개5', -1], ['개6', 1], ['개7', 0], ['바6', 1]].map(([code, value]) => ({ code, value, status: 'observed', validity: 'valid', opportunity: 'present', evidence: [{ video_id: video.video_id, video_sha256: video.sha256, window_id: 'entry', start_seconds: 0, end_seconds: .8, observed_seconds: .8, note: '합성 입장 실제 확인 근거' }] }));
  expect((await page.request.put(`/api/sheets/${assigned.sheet_id}`, { headers, data: { expected_revision: 1, observations } })).status()).toBe(200);
  await page.getByRole('button', { name: '독립 채점', exact: true }).click();
  await page.getByRole('button', { name: 'v3basic 독립 채점 열기', exact: true }).click();
  await page.getByRole('button', { name: '내 시트 열기', exact: true }).click();
  const sheet = page.getByLabel('내 채점 시트', { exact: true });
  await sheet.getByLabel('원코드/항목 검색', { exact: true }).fill('바6');
  const vocal = sheet.getByLabel('바6 원관찰', { exact: true });
  await vocal.getByText('바6 전체 청취·누적 발성량', { exact: true }).click();
  await vocal.getByRole('button', { name: '청취 기록 추가', exact: true }).click();
  await vocal.getByLabel('실제 청취 초', { exact: true }).fill('1');
  await vocal.getByLabel('누적 발성 초', { exact: true }).fill('.3');
  await vocal.getByLabel('전체 실제 구간 판독 완료', { exact: true }).check();
  await vocal.getByLabel('청취·발성량 근거', { exact: true }).fill('실제 전체1초와 누적0.3초');
  await sheet.getByRole('button', { name: '채점 초안 저장', exact: true }).click();
  await expect(sheet.getByRole('button', { name: '채점 초안 저장', exact: true })).toBeDisabled();
  const basic = page.getByLabel('기본 계산과 판정', { exact: true });
  await basic.getByRole('button', { name: '선택 시트 r3 기본 계산', exact: true }).click();
  const content = basic.getByLabel('고정 기본 결과 내용', { exact: true });
  await expect(content).toContainText('입력 시트 r3 · 판정 r1');
  await expect(content.locator('tr').filter({ hasText: 'vocal_바6' })).toContainText('1 · 계산됨');
  const entry = content.getByLabel('입장 판단 기록', { exact: true });
  await entry.getByLabel('입장 판단 상태', { exact: true }).selectOption('complete');
  await entry.getByText('입장 판단 근거·반대 근거 선택', { exact: true }).click();
  await entry.getByLabel('개5 · -1 · valid', { exact: true }).check();
  await entry.getByLabel('개6 · 1 · valid', { exact: true }).check();
  await entry.getByLabel('입장 판단 관찰 기회', { exact: true }).fill('실제 입장과 물건 탐색을 각 원창에서 확인');
  await entry.getByLabel('입장 판단 반대 근거 검토', { exact: true }).fill('고정 입력에서 추가 반대 근거 미관찰');
  await entry.getByLabel('입장 판단 사유', { exact: true }).fill('반대 부호 원값을 상쇄하지 않고 서로 다른 반응으로 보존');
  await content.getByLabel('판정 수정 사유', { exact: true }).fill('영상 다중 근거 확인');
  await content.getByRole('button', { name: '기본 판정 저장', exact: true }).click();
  await expect(content).toContainText('입력 시트 r3 · 판정 r2');
  await expect(entry.getByLabel('입장 판단 상태', { exact: true })).toHaveValue('complete');
  const resultId = await basic.getByLabel('고정 기본 결과', { exact: true }).inputValue();
  const result = await (await page.request.get(`/api/basic-results/${resultId}`)).json();
  expect(result.document.decisions.find((d: { key: string }) => d.key === 'attachment').status).toBe('held');
  await entry.getByLabel('입장 판단 사유', { exact: true }).fill('미저장 판정 보존');
  const current = result.document.decisions[2];
  expect((await page.request.put(`/api/basic-results/${resultId}/decisions`, { headers, data: { expected_revision: 2, reason: '다른 창 동시 수정', decisions: [{ key: current.key, label: current.label, status: 'draft', evidence_codes: current.evidence_codes, counter_codes: [], opportunity_note: current.opportunity_note, reason: '동시 수정 초안' }] } })).status()).toBe(200);
  await content.getByLabel('판정 수정 사유', { exact: true }).fill('충돌 검증');
  await content.getByRole('button', { name: '기본 판정 저장', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('다른 판정 수정');
  await expect(entry.getByLabel('입장 판단 사유', { exact: true })).toHaveValue('미저장 판정 보존');
  page.once('dialog', dialog => dialog.accept());
  await content.getByRole('button', { name: '미저장 판정 버리고 최신 조회', exact: true }).click();
  await expect(content).toContainText('판정 r3');
  await content.getByLabel('기본 판정 보존본', { exact: true }).selectOption('2');
  await expect(entry.getByLabel('입장 판단 상태', { exact: true })).toHaveValue('complete');
  await expect(entry.getByLabel('입장 판단 상태', { exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '알림 닫기', exact: true }).click();
  await content.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: testInfo.outputPath('C06_계산과판정.png') });
  await page.setViewportSize({ width: 360, height: 780 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await content.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: testInfo.outputPath('C06_계산과판정_360px.png') });
  await entry.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: testInfo.outputPath('C06_판정입력_360px.png') });
});
