import { test, expect, type APIRequestContext, type Page } from '@playwright/test';
import { execFileSync } from 'node:child_process';

const headers = { 'X-KDOG-Request': '1' };
const password = 'Browser-test-only-42';

test('RP02 completed attachment opinion starts a separate run and pins its result explicitly', async ({ page, request }, testInfo) => {
  test.setTimeout(120000);
  const data = await fixture(request, 'rp02-opinion');
  const opinion = await request.put(data.path + '/opinions-s1', { headers, data: { expected_revision: 0, basic: data.basicRef, evaluator: '합성 해석 검토자', completion_requested: true, domains: [{ domain: 'attachment', text: '재회 관찰을 더 확인해야 합니다.' }], reason: '합성 완료 애착 의견' } });
  expect(opinion.status(), await opinion.text()).toBe(200);
  const current = await opinion.json();
  const reference = { run_id: 'synthetic-attachment', ref: 'runs/synthetic-attachment/attempt/output.json', hash: 'a'.repeat(64) };
  const view = { run_id: reference.run_id, status: 'queued', updated_at: 'synthetic', reserved_calls: 0, judgement_status: 'completed_opinion_inference', reference: null };
  let requests = 0;
  const requestIds: string[] = [];
  await page.route('**/opinions-s1/attachment-runs', async route => {
    expect(route.request().method()).toBe('POST');
    expect(route.request().postDataJSON()).toMatchObject({ basic: data.basicRef, opinion: current.reference });
    requests++;
    requestIds.push(route.request().postDataJSON().request_id);
    if (requests === 1 || requests === 3) { await route.abort('failed'); return; }
    await route.fulfill({ status: 201, json: view });
  });
  await page.route('**/opinions-s1/attachment-runs/synthetic-attachment', route => route.fulfill({ json: { ...view, status: 'succeeded', reserved_calls: 1, reference } }));
  await login(page, 'operator'); await open(page, 'rp02-opinion');
  const panel = page.getByRole('region', { name: 'S1 의견과 최종 결과', exact: true });
  await panel.getByLabel('행사에 사용할 고정 기본 결과', { exact: true }).selectOption(`${data.basicRef.result_id}:${data.basicRef.revision}`);
  const section = panel.getByRole('region', { name: '완료 애착 의견 AI 해석', exact: true });
  await section.getByRole('button', { name: '완료 애착 의견을 AI로 해석', exact: true }).click();
  await expect(section).toContainText('같은 입력으로 다시 누르면 동일 요청 ID');
  await section.getByRole('button', { name: '완료 애착 의견을 AI로 해석', exact: true }).click();
  await expect(section).toContainText('해석 실행 queued');
  await section.getByRole('button', { name: '애착 해석 상태 새로고침', exact: true }).click();
  await expect(section).toContainText('이 해석 판본을 새 최종본에 연결합니다.');
  await section.getByRole('button', { name: '완료 애착 의견을 AI로 해석', exact: true }).click();
  await expect(section).toContainText('같은 입력으로 다시 누르면 동일 요청 ID');
  await section.getByRole('button', { name: '완료 애착 의견을 AI로 해석', exact: true }).click();
  await expect(section).toContainText('해석 실행 queued');
  await section.getByRole('button', { name: '애착 해석 상태 새로고침', exact: true }).click();
  await expect(section).toContainText('이 해석 판본을 새 최종본에 연결합니다.');
  await page.route('**/final-results-s1', async route => {
    if (route.request().method() !== 'POST') { await route.continue(); return; }
    expect(route.request().postDataJSON()).toMatchObject({ attachment_inference: reference, opinion: current.reference });
    await route.fulfill({ status: 409, json: { detail: '합성 UI 시험: 가상 해석 참조를 실제 최종본으로 채택하지 않음' } });
  });
  await panel.getByLabel('최종본 고정 사유', { exact: true }).fill('별도 해석 고정 전달 검증');
  await panel.getByRole('button', { name: '선택한 판본으로 새 최종본 생성', exact: true }).click();
  await expect(panel.getByRole('alert')).toContainText('합성 UI 시험');
  expect(requests).toBe(4);
  expect(requestIds[0]).toBeTruthy();
  expect(requestIds[1]).toBe(requestIds[0]);
  expect(requestIds[2]).not.toBe(requestIds[0]);
  expect(requestIds[3]).toBe(requestIds[2]);
  await page.setViewportSize({ width: 360, height: 800 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await section.screenshot({ path: testInfo.outputPath('rp02-opinion-inference-360.png'), animations: 'disabled' });
});
async function login(page: Page, username: string) {
  await page.goto('/'); await page.getByLabel('계정', { exact: true }).fill(username); await page.getByLabel('비밀번호', { exact: true }).fill(password);
  await page.getByRole('button', { name: '로그인', exact: true }).click(); await expect(page.getByRole('button', { name: '로그아웃', exact: true })).toBeVisible();
}
async function open(page: Page, participant: string) {
  await page.getByRole('button', { name: '독립 채점', exact: true }).click(); await page.getByRole('button', { name: `${participant} 독립 채점 열기`, exact: true }).click();
}
async function fixture(request: APIRequestContext, participant: string) {
  await request.post('/api/auth/login', { headers, data: { username: 'operator', password } });
  let item = await (await request.post('/api/cases', { headers, data: { event_id: 'S1-OPINION', participant_id: participant, dog_name: '최종 의견 합성견' } })).json();
  const path = `/api/cases/${item.case_id}/sessions/${item.selected_session_id}`;
  const bytes = execFileSync('ffmpeg', ['-v', 'error', '-nostdin', '-f', 'lavfi', '-i', 'testsrc2=size=64x64:rate=2:duration=4', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-f', 'mp4', '-movflags', 'frag_keyframe+empty_moov', 'pipe:1']);
  const receipt = await (await request.post('/api/uploads', { headers, data: { request_id: participant + '-media', filename: 'synthetic-opinion.mp4', expected_size: bytes.length } })).json();
  expect((await request.put(`/api/uploads/${receipt.upload_id}/content`, { headers, params: { request_id: receipt.request_id }, data: bytes })).status()).toBe(200);
  expect((await request.post(`/api/uploads/${receipt.upload_id}/link`, { headers, data: { case_id: item.case_id, session_id: item.selected_session_id, camera_id: 'CAM1', expected_revision: item.input_revision } })).status()).toBe(200);
  item = await (await request.get(`/api/cases/${item.case_id}`)).json(); const video = item.manifest.sessions[0].videos[0];
  const recording = { video_id: video.video_id, confirmed: true, procedure_edition: 's1_confirmed', procedure_note: '의견 고정 판본 합성 fixture', segments: ['entry', 'baseline', 'alone', 'reunion', 'ignore', 'walk', 'stranger', 'exit'].map(segment => ({ segment, video_id: video.video_id, state: ['entry', 'stranger'].includes(segment) ? 'performed' : 'not_performed', start_sec: segment === 'entry' ? 0 : segment === 'stranger' ? 2 : null, end_sec: segment === 'entry' ? 2 : segment === 'stranger' ? 4 : null, reason: ['entry', 'stranger'].includes(segment) ? null : '합성 미실시' })) };
  const capture = await request.put(path + '/recording-s1', { headers, data: { expected_revision: item.input_revision, recording } }); expect(capture.status(), await capture.text()).toBe(200); item = await capture.json();
  const sheet = await (await request.post(path + '/sheets-s1', { headers, data: { expected_revision: item.input_revision, assigned_username: 'operator', rater_id: participant, rater_name: '행사 담당 평가자' } })).json();
  const evidence = { video_id: video.video_id, video_sha256: video.sha256, camera_id: 'CAM1', window_id: 'stranger_whole', start_seconds: 2, end_seconds: 4, observed_seconds: 2, note: '동일 장면에서 구분한 지지·반대 근거' };
  const catalog = await (await request.get('/api/catalog/behavior-s1')).json();
  const observations = catalog.items.filter((value: { usage: string; optional: boolean }) => value.usage !== 'automatic' && !value.optional).map((value: { code: string }) => ['보23', '보16'].includes(value.code) ? { code: value.code, value: value.code === '보23' ? 2 : 1, status: 'observed', validity: 'valid', opportunity: 'present', reason: null, evidence: [evidence] } : { code: value.code, value: null, status: 'unobserved', reason: '합성 시험 관찰 미실시' });
  const written = await request.put(`/api/score-sheets-s1/${sheet.sheet_id}`, { headers, data: { expected_revision: sheet.revision, observations, reason: '고정 원관찰 합성 기록' } }); expect(written.status(), await written.text()).toBe(200);
  const saved = await written.json(); const submitted = await (await request.post(`/api/score-sheets-s1/${sheet.sheet_id}/submit`, { headers, data: { expected_revision: saved.revision, reason: '독립 제출 합성 기록' } })).json();
  const calculated = await request.post(`/api/score-sheets-s1/${sheet.sheet_id}/basic-results-s1`, { headers, data: { input: { sheet_id: sheet.sheet_id, revision: submitted.revision, ref: submitted.manifest_ref, hash: submitted.manifest_hash } } }); expect(calculated.status(), await calculated.text()).toBe(201);
  const initial = await calculated.json();
  const revised = await request.put(`/api/basic-results-s1/${initial.summary.result_id}/judgements`, { headers, data: { expected_revision: initial.summary.revision, reason: '고정 수동 기본 판정', decisions: [{ key: 'owner_type', label: '통제형', status: 'complete', reason: '실제 두 항목에서 근거를 검토한 수동 선택', evidence_codes: ['보23', '보16'], counter_codes: ['보16'], counter_note: '같은 장면의 보16은 반대 근거로 검토' }] } }); expect(revised.status(), await revised.text()).toBe(200);
  const basic = await revised.json(); const basicRef = { result_id: basic.summary.result_id, revision: basic.summary.revision, ref: basic.summary.manifest_ref, hash: basic.summary.manifest_hash };
  return { item, path, sheet: submitted, basic, basicRef, observations, evidence };
}

test('S1 opinions preserve completion gates, typed evidence, conflict drafts and immutable final priority', async ({ page, request }, testInfo) => {
  test.setTimeout(180000); page.setDefaultTimeout(15000); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const data = await fixture(request, 's1opinion'); const { path, basic, basicRef } = data;
  await login(page, 'operator'); await open(page, 's1opinion');
  const panel = page.getByRole('region', { name: 'S1 의견과 최종 결과', exact: true });
  await panel.getByLabel('행사에 사용할 고정 기본 결과', { exact: true }).selectOption(`${basicRef.result_id}:${basicRef.revision}`);
  const editor = panel.getByRole('region', { name: 'S1 의견 편집', exact: true }); await expect(editor).toBeVisible();
  async function assemble(reason: string) {
    await panel.getByLabel('최종본 고정 사유', { exact: true }).fill(reason);
    const pending = page.waitForResponse(value => value.url().endsWith('/final-results-s1') && value.request().method() === 'POST');
    await panel.getByRole('button', { name: '선택한 판본으로 새 최종본 생성', exact: true }).click();
    const result = await pending; expect(result.status(), await result.text()).toBe(201);
    await expect(panel.getByRole('region', { name: 'S1 보존 최종본', exact: true }).getByText(reason, { exact: false })).toBeVisible();
    return result.json();
  }
  const noOpinion = await assemble('의견 없는 기본 우선순위 확인');
  expect(noOpinion.document.domains.find((row: { domain: string }) => row.domain === 'education_attitude')).toMatchObject({ label: '통제형', source: 'manual_selection' });
  await editor.getByLabel('의견 평가자', { exact: true }).fill('합성 담당 평가자'); await editor.getByLabel('D39 우선 도움', { exact: true }).fill('짧고 예측 가능한 일상부터 도움');
  await editor.getByLabel('B40 의견 완료 요청', { exact: true }).check();
  await editor.getByLabel('의견 저장·상태 변경 사유', { exact: true }).fill('D39 단독 완료 불충족 확인');
  await editor.getByRole('button', { name: '의견 저장·완료 조건 확인', exact: true }).click();
  await expect(editor.getByText(/D33~D38 실질 영역 의견 없음/)).toBeVisible();
  await expect(editor.getByText(/실제 완료: 미충족 · 작성 중 · r1/)).toBeVisible();
  const education = editor.getByRole('region', { name: '교육태도 의견', exact: true });
  await education.getByLabel('교육태도 의견 원문', { exact: true }).fill('낯선 상황에서 신호를 기다리고 조율하는 양상을 관찰했습니다.');
  await education.getByLabel('교육태도 명시 유형', { exact: true }).selectOption('조율형');
  await education.getByLabel('교육태도 유형 근거', { exact: true }).fill('지지와 반대 행동을 함께 확인한 해석');
  await education.getByText('교육태도 근거 항목·반대 근거·고정 장면', { exact: true }).click();
  await education.getByLabel('교육태도 근거 보23', { exact: true }).check(); await education.getByLabel('교육태도 근거 보16', { exact: true }).check();
  await education.getByLabel('교육태도 반대 근거 보16', { exact: true }).check();
  await education.getByLabel('교육태도 반대 근거 검토', { exact: true }).fill('같은 장면의 반대 행동도 누락하지 않았습니다.');
  await education.getByLabel('교육태도 지정 장면 1', { exact: true }).check();
  await expect(education.getByLabel('교육태도 지정 장면 2', { exact: true })).toHaveCount(0);
  await editor.getByLabel('의견 저장·상태 변경 사유', { exact: true }).fill('한 영역 의견과 근거를 완료');
  await editor.getByRole('button', { name: '의견 저장·완료 조건 확인', exact: true }).click(); await expect(editor.getByText(/실제 완료: 충족 · 완료 · r2/)).toBeVisible();
  const opinion = await (await page.request.get(path + '/opinions-s1')).json();
  expect(opinion.document.domains.find((row: { domain: string }) => row.domain === 'education_attitude')).toMatchObject({ label: '조율형', counter_codes: ['보16'], scene_refs: [data.evidence] });
  const completed = await assemble('완료 교육태도 의견만 영역 우선 적용');
  expect(completed.document.domains.filter((row: { source: string }) => row.source === 'completed_opinion')).toHaveLength(1);
  expect(completed.document.domains.find((row: { domain: string }) => row.domain === 'education_attitude')).toMatchObject({ label: '조율형', source: 'completed_opinion' });
  expect(completed.document.basic).toMatchObject(basicRef); expect(completed.document.basic_document.calculations).toEqual(basic.document.calculations);
  await editor.getByLabel('의견 저장·상태 변경 사유', { exact: true }).fill('완료 후 재개방'); await editor.getByRole('button', { name: '의견 재개방', exact: true }).click();
  await expect(editor.getByText(/작성 중 · r3/)).toBeVisible(); await education.getByLabel('교육태도 의견 원문', { exact: true }).fill('미저장 지역 의견 원문');
  expect((await page.request.put(`/api/basic-results-s1/${basicRef.result_id}/judgements`, { headers, data: { expected_revision: basicRef.revision, reason: '의견 편집 중 새 기본 판본', decisions: [{ key: 'owner_type', label: '통제형', status: 'complete', evidence_codes: ['보23', '보16'], counter_codes: ['보16'], counter_note: '반대 근거를 유지한 새 판본', reason: '다른 창에서 기본 판정 근거 보완' }] } })).status()).toBe(200);
  await panel.getByRole('button', { name: '의견·최종 목록 새로고침', exact: true }).click();
  await expect(education.getByLabel('교육태도 의견 원문', { exact: true })).toHaveValue('미저장 지역 의견 원문');
  await expect(panel.getByLabel('행사에 사용할 고정 기본 결과', { exact: true })).toHaveValue(`${basicRef.result_id}:${basicRef.revision}`);
  const current = (await (await page.request.get(path + '/opinions-s1')).json()).document;
  expect((await page.request.put(path + '/opinions-s1', { headers, data: { expected_revision: current.revision, basic: current.basic, evaluator: current.evaluator, completion_requested: false, priority_help: current.priority_help, domains: current.domains.map((row: { domain: string }) => row.domain === 'education_attitude' ? { ...row, text: '다른 창에 저장한 의견' } : row), reason: '동시 편집 fixture' } })).status()).toBe(200);
  await panel.getByRole('button', { name: '의견·최종 목록 새로고침', exact: true }).click(); await expect(editor.getByText(/다른 의견 판본이 저장되었습니다/)).toBeVisible();
  await editor.getByLabel('의견 저장·상태 변경 사유', { exact: true }).fill('충돌 원문 보존'); await editor.getByRole('button', { name: '의견 저장·완료 조건 확인', exact: true }).click();
  await expect(editor.getByRole('alert')).toContainText('다른 의견'); await expect(education.getByLabel('교육태도 의견 원문', { exact: true })).toHaveValue('미저장 지역 의견 원문');
  page.once('dialog', dialog => dialog.accept()); await editor.getByRole('button', { name: '미저장 의견 버리고 최신 조회', exact: true }).click();
  await expect(education.getByLabel('교육태도 의견 원문', { exact: true })).toHaveValue('다른 창에 저장한 의견');
  await editor.getByLabel('의견 저장·상태 변경 사유', { exact: true }).fill('현재 의견 철회'); await editor.getByRole('button', { name: '의견 철회', exact: true }).click(); await expect(editor.getByText(/철회 · r5/)).toBeVisible();
  const withdrawn = await assemble('철회 뒤 남은 수동 선택으로 돌아감');
  expect(withdrawn.document.domains.find((row: { domain: string }) => row.domain === 'education_attitude')).toMatchObject({ label: '통제형', source: 'manual_selection' });
  expect(withdrawn.document.priority_help).toBeNull();
  expect((await (await page.request.get(path + `/final-results-s1/${completed.reference.final_id}`)).json())).toEqual(completed);
  expect((await (await page.request.get(`/api/basic-results-s1/${basicRef.result_id}/revisions/${basicRef.revision}`)).json()).document).toEqual(basic.document);
  await page.setViewportSize({ width: 360, height: 800 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await panel.getByRole('region', { name: 'S1 보존 최종본', exact: true }).screenshot({ path: testInfo.outputPath('final-s1-360.png'), animations: 'disabled' });
  expect(errors).toEqual([]);
});

test('S1 other-author interpretations require explicit disclosure and preserve independent submissions', async ({ page, request }, testInfo) => {
  test.setTimeout(180000); page.setDefaultTimeout(15000); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const data = await fixture(request, 's1disclosure'); const { item, path, sheet, basicRef, observations } = data;
  const admin = await (await request.post(path + '/sheets-s1', { headers, data: { expected_revision: item.input_revision, source_sheet_id: sheet.sheet_id, assigned_username: 'admin', rater_id: 's1-admin-independent', rater_name: '독립 행사 검토자' } })).json();
  const opinion = await (await request.put(path + '/opinions-s1', { headers, data: { expected_revision: 0, basic: basicRef, evaluator: '최초 담당자', completion_requested: true, domains: [{ domain: 'education_attitude', text: '공개 전에는 숨겨야 하는 타인 의견' }], reason: '합성 타인 해석' } })).json();
  const final = await (await request.post(path + '/final-results-s1', { headers, data: { basic: basicRef, opinion: opinion.reference, reason: '합성 타인 최종본' } })).json();
  await login(page, 'admin');
  const adminPath = `/api/score-sheets-s1/${admin.sheet_id}`;
  const adminDraft = await (await page.request.put(adminPath, { headers, data: { expected_revision: admin.revision, observations, reason: '공개 전 독립 원자료' } })).json();
  const adminSubmit = await (await page.request.post(adminPath + '/submit', { headers, data: { expected_revision: adminDraft.revision, reason: '독립 완료' } })).json();
  const independent = (await (await page.request.get(adminPath)).json()).document;
  expect((await request.post(adminPath + '/grants', { headers, data: { expected_revision: adminSubmit.revision, target_sheet_id: sheet.sheet_id, target_revision: sheet.revision, reason: '독립 제출 이후 원자료 공개 허용' } })).status()).toBe(200);
  await open(page, 's1disclosure'); const panel = page.getByRole('region', { name: 'S1 의견과 최종 결과', exact: true });
  await panel.getByLabel('해석 공개를 기록할 본인 제출 시트', { exact: true }).selectOption(admin.sheet_id);
  await expect(panel.getByText('공개 전에는 숨겨야 하는 타인 의견', { exact: true })).toHaveCount(0);
  expect((await page.request.get(path + '/opinions-s1', { params: { viewer_sheet_id: admin.sheet_id } })).status()).toBe(403);
  expect((await page.request.get(path + `/final-results-s1/${final.reference.final_id}`, { params: { viewer_sheet_id: admin.sheet_id } })).status()).toBe(403);
  await page.getByRole('button', { name: '내 시트 열기', exact: true }).click();
  const sheetEditor = page.getByRole('region', { name: '내 S1 채점 시트', exact: true });
  await sheetEditor.getByText('명시 공개된 완료본', { exact: true }).click(); await sheetEditor.getByRole('button', { name: /공개 완료본 r.*열고 노출 기록/ }).click();
  await expect(sheetEditor.getByRole('heading', { name: '독립 행사 검토자 · 공개 후 검수', exact: true })).toBeVisible();
  const candidates = await page.request.get(path + '/final-results-s1/candidates', { params: { viewer_sheet_id: admin.sheet_id } });
  expect(candidates.status(), await candidates.text()).toBe(200); expect(await candidates.json()).toEqual(expect.arrayContaining([expect.objectContaining({ result_id: basicRef.result_id, revision: basicRef.revision })]));
  await panel.getByRole('button', { name: '의견·최종 목록 새로고침', exact: true }).click();
  await panel.getByLabel('행사에 사용할 고정 기본 결과', { exact: true }).selectOption(`${basicRef.result_id}:${basicRef.revision}`);
  await expect(panel.getByRole('region', { name: 'S1 의견 편집', exact: true })).toHaveCount(0);
  await panel.getByLabel('해석 공개 사유', { exact: true }).fill('독립 제출 이후 행사 해석 확인');
  const reveal = page.waitForResponse(value => value.url().endsWith('/opinions-s1/reveal') && value.request().method() === 'POST');
  await panel.getByRole('button', { name: '현재 의견을 명시 공개하고 노출 기록', exact: true }).click();
  expect((await reveal).status()).toBe(200);
  await expect(panel.getByLabel('교육태도 의견 원문', { exact: true })).toHaveValue('공개 전에는 숨겨야 하는 타인 의견');
  const after = await (await page.request.get(adminPath)).json(); expect(after.document.interpretation_exposures).toHaveLength(1); expect(after.document.purpose).toBe('review');
  expect(after.document.initial_submission.revision).toBe(independent.revision);
  expect((await (await page.request.get(adminPath + `/revisions/${independent.revision}`)).json())).toEqual(independent);
  await panel.getByRole('button', { name: '이 최종본을 명시 공개하고 노출 기록', exact: true }).click();
  const snapshot = panel.getByRole('region', { name: 'S1 보존 최종본', exact: true }); await expect(snapshot.getByText('공개 전에는 숨겨야 하는 타인 의견', { exact: true })).toBeVisible();
  expect((await (await page.request.get(adminPath)).json()).document.interpretation_exposures).toHaveLength(2);
  await expect(sheetEditor.getByRole('heading', { name: '독립 행사 검토자 · 공개 후 검수', exact: true })).toBeVisible();
  await expect(sheetEditor.getByText(/다른 평가자의 의견·최종 해석을 열람했습니다/)).toBeVisible();
  await sheetEditor.getByLabel('보존본 조회', { exact: true }).selectOption(String(independent.revision));
  await expect(sheetEditor.getByRole('heading', { name: '독립 행사 검토자 · 독립 원자료', exact: true })).toBeVisible();
  await expect(sheetEditor.getByText('보존본 읽기 전용', { exact: true })).toBeVisible();
  await sheetEditor.getByLabel('보존본 조회', { exact: true }).selectOption('');
  await expect(sheetEditor.getByRole('heading', { name: '독립 행사 검토자 · 공개 후 검수', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 360, height: 800 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await snapshot.screenshot({ path: testInfo.outputPath('interpretation-reveal-s1-360.png'), animations: 'disabled' });
  const current = await (await request.get(`/api/score-sheets-s1/${sheet.sheet_id}`)).json();
  expect((await request.post(`/api/score-sheets-s1/${sheet.sheet_id}/assignment`, { headers, data: { expected_revision: current.summary.revision, active: false, reason: '기본 입력 권한 철회' } })).status()).toBe(200);
  await panel.getByRole('button', { name: '의견·최종 목록 새로고침', exact: true }).click();
  await expect(snapshot).toHaveCount(0); await expect(panel.getByRole('region', { name: 'S1 의견 편집', exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
});
