import { test, expect } from '@playwright/test';

const headers = { 'X-KDOG-Request': '1' };

test('회차 초기화와 자동 조회 중 편집 revision 보호', async ({ page }, testInfo) => {
  await page.goto('/');
  await page.getByLabel('계정', { exact: true }).fill('operator');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('button', { name: '로그아웃' })).toBeVisible();
  let item = await (await page.request.post('/api/cases', { headers, data: { event_id: 'REC-EDIT', participant_id: 'freeze', dog_name: '회차 검증견' } })).json();
  item = await (await page.request.post(`/api/cases/${item.case_id}/videos`, { headers, params: { session_id: item.selected_session_id, expected_revision: item.input_revision, filename: 'synthetic.mp4' }, data: Buffer.from('synthetic') })).json();
  const sessionId = item.selected_session_id;
  const videoId = item.manifest.sessions[0].videos[0].video_id;
  const windows = ['entry', 'baseline', 'alone', 'stranger', 'reunion', 'ignore', 'walk', 'exit'].map((segment, i) => ({ segment, start_sec: i * 5, end_sec: i * 5 + 4 }));
  const endpoint = `/api/cases/${item.case_id}/sessions/${sessionId}/segments`;
  item = await (await page.request.put(endpoint, { headers, data: { expected_revision: item.input_revision, video_id: videoId, windows, confirm: true } })).json();
  await page.getByRole('button', { name: '촬영', exact: true }).click();
  await page.getByRole('button', { name: 'freeze 촬영 열기' }).click();
  const panel = page.getByLabel('촬영 자료');
  await panel.getByRole('button', { name: '확정본 수정 시작' }).click();
  await panel.getByLabel('퇴장 끝', { exact: true }).fill('0:40');
  item = await (await page.request.put(endpoint, { headers, data: { expected_revision: item.input_revision, video_id: videoId, windows: windows.map(w => ({ ...w, start_sec: w.start_sec + 50, end_sec: w.end_sec + 50 })), confirm: true } })).json();
  await expect(panel.getByText(/다른 변경이 저장됨/)).toBeVisible();
  await expect(panel.locator('summary').filter({ hasText: '현재 촬영 메모 수정' })).toHaveCount(1);
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('0:40');
  const conflict = page.waitForResponse(r => r.url().endsWith('/segments') && r.request().method() === 'PUT');
  await panel.getByRole('button', { name: '8구간 초안 저장', exact: true }).click();
  expect((await conflict).status()).toBe(409);
  let persisted = await (await page.request.get(`/api/cases/${item.case_id}`)).json();
  expect(persisted.manifest.sessions[0].segments.windows[7].end_sec).toBe(89);
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('0:40');
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.screenshot({ path: testInfo.outputPath('recording-conflict-768.png'), fullPage: true });
  page.once('dialog', dialog => dialog.accept());
  await panel.getByRole('button', { name: '최신 값 불러오기' }).click();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('1:29.0');
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toBeDisabled();
  await panel.getByText('재촬영 세션 추가', { exact: true }).click();
  await panel.getByRole('button', { name: '새 촬영 시작', exact: true }).click();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('');
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toBeEnabled();
  persisted = await (await page.request.get(`/api/cases/${item.case_id}`)).json();
  expect(persisted.manifest.sessions[0].segments.windows[7].end_sec).toBe(89);
  expect(persisted.manifest.sessions[1].segments).toBeNull();
  const secondId = persisted.selected_session_id;
  persisted = await (await page.request.post(`/api/cases/${item.case_id}/videos`, { headers, params: { session_id: secondId, expected_revision: persisted.input_revision, filename: 'second.mp4' }, data: Buffer.from('synthetic') })).json();
  persisted = await (await page.request.post(`/api/cases/${item.case_id}/sessions`, { headers, data: { session_id: sessionId, expected_revision: persisted.input_revision } })).json();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('1:29.0');
  await panel.getByRole('button', { name: '확정본 수정 시작' }).click();
  await panel.getByLabel('퇴장 끝', { exact: true }).fill('1:30');
  page.once('dialog', dialog => dialog.dismiss());
  persisted = await (await page.request.post(`/api/cases/${item.case_id}/sessions`, { headers, data: { session_id: secondId, expected_revision: persisted.input_revision } })).json();
  await expect(panel.getByText(/다른 변경이 저장됨/)).toBeVisible();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('1:30');
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '전체 목록으로 돌아가기' }).click();
  await page.getByRole('button', { name: 'freeze 촬영 열기' }).click();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('');
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '로그아웃' }).click();
  await page.getByLabel('계정', { exact: true }).fill('reviewer');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await page.getByRole('button', { name: '촬영', exact: true }).click();
  await page.getByRole('button', { name: 'freeze 촬영 열기' }).click();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toBeDisabled();
  await expect(panel.getByRole('button', { name: '8구간 초안 저장', exact: true })).toHaveCount(0);
  expect((await page.request.put(endpoint, { headers, data: { expected_revision: persisted.input_revision, video_id: videoId, windows, confirm: false } })).status()).toBe(403);
});

test('촬영 menu: several files with a partial failure, eight segment times, order check, confirm and lock', async ({ page }, testInfo) => {
  await page.goto('/');
  await page.getByLabel('계정', { exact: true }).fill('operator');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('button', { name: '로그아웃' })).toBeVisible();
  await page.request.post('/api/cases', { headers, data: { event_id: 'REC-TEST', participant_id: '0021', dog_name: '촬영 검증견', sequence_no: 21 } });
  await page.getByRole('button', { name: '촬영', exact: true }).click();
  await expect(page.getByRole('heading', { name: '촬영', exact: true })).toBeVisible();
  const row = page.getByRole('row', { name: /0021/ });
  await expect(row.getByRole('cell', { name: '없음', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '0021 촬영 열기' }).click();
  const panel = page.getByLabel('촬영 자료');
  let failed = false;
  await page.route('**/api/cases/*/videos?*', async route => {
    const name = new URL(route.request().url()).searchParams.get('filename')!;
    if (name === 'second.mp4' && !failed) { failed = true; await route.fulfill({ status: 503, json: { detail: '합성 일시 장애' } }); }
    else await route.continue();
  });
  await panel.getByLabel('영상 파일', { exact: true }).setInputFiles(['first.mp4', 'second.mp4', 'third.mp4'].map(name => ({ name, mimeType: 'video/mp4', buffer: Buffer.from(name) })));
  await panel.getByRole('button', { name: '영상 등록', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '1개 저장 · 1개 실패 · 1개 대기' })).toBeVisible();
  await panel.getByRole('button', { name: '영상 등록', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '3개 저장 · 0개 실패 · 0개 대기' })).toBeVisible();
  await expect(panel.getByText('3 FILES', { exact: true })).toBeVisible();
  await expect(panel.getByText('카메라', { exact: false })).toHaveCount(0);
  await panel.getByLabel('구간 기준 영상').nth(1).check();
  const order = ['입장', '기준', '혼자', '낯선 사람', '재회', '무시', '걷기', '퇴장'];
  for (const [i, label] of order.entries()) {
    await panel.getByLabel(`${label} 시작`, { exact: true }).fill(`${Math.floor(i * 20 / 60)}:${String(i * 20 % 60).padStart(2, '0')}`);
    await panel.getByLabel(`${label} 끝`, { exact: true }).fill(`${Math.floor((i * 20 + 15) / 60)}:${String((i * 20 + 15) % 60).padStart(2, '0')}`);
  }
  await panel.getByLabel('기준 끝', { exact: true }).fill('0:45');  // overlaps 혼자 0:40
  await panel.getByRole('button', { name: '8구간 초안 저장', exact: true }).click();
  await expect(panel.getByText('기준 끝 0:45가 혼자 시작 0:40보다 늦습니다. 구간 순서를 확인하세요.', { exact: true })).toBeVisible();
  await panel.getByLabel('기준 끝', { exact: true }).fill('0:35');
  await panel.getByRole('button', { name: '8구간 초안 저장', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '초안으로 저장했습니다' })).toBeVisible();
  await expect(panel.getByText('초안', { exact: true })).toBeVisible();
  await panel.getByRole('button', { name: '8구간 확정', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '확정했습니다' })).toBeVisible();
  await expect(panel.getByText('확정', { exact: true })).toBeVisible();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toBeDisabled();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toHaveValue('2:35.0');
  await page.screenshot({ path: testInfo.outputPath('recording-confirmed.png'), fullPage: true, animations: 'disabled' });
  await page.reload();
  await page.getByRole('button', { name: '촬영', exact: true }).click();
  await page.getByRole('button', { name: '0021 촬영 열기' }).click();
  await expect(page.getByLabel('촬영 자료').getByLabel('입장 시작', { exact: true })).toBeDisabled();
  await page.getByLabel('촬영 자료').getByRole('button', { name: '확정본 수정 시작' }).click();
  await expect(page.getByLabel('촬영 자료').getByLabel('입장 시작', { exact: true })).toBeEnabled();
  await expect(panel.getByText('아직 저장된 확정본은 유지됩니다. 초안 저장 시 미확정으로 바뀝니다.', { exact: true })).toBeVisible();
  const item = (await (await page.request.get('/api/cases')).json()).find((c: { participant_id: string }) => c.participant_id === '0021');
  expect(item.manifest.sessions[0].segments.confirmed).toBe(true);
  expect(item.manifest.sessions[0].segments.windows[7]).toEqual({ segment: 'exit', start_sec: 140, end_sec: 155 });
  await expect(panel.getByRole('button', { name: '지금 시각', exact: true }).first()).toBeDisabled();
  await panel.getByLabel('퇴장 끝', { exact: true }).fill('2:20');
  await panel.getByRole('button', { name: '8구간 확정', exact: true }).click();
  await expect(panel.getByText('퇴장 끝은 시작보다 늦어야 확정할 수 있습니다.', { exact: true })).toBeVisible();
  await panel.getByLabel('퇴장 끝', { exact: true }).fill('2:36');
  await panel.getByRole('button', { name: '8구간 초안 저장', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '초안으로 저장했습니다' })).toBeVisible();
  let saved = await (await page.request.get(`/api/cases/${item.case_id}`)).json();
  expect(saved.manifest.sessions[0].segments.confirmed).toBe(false);
  await panel.getByRole('button', { name: '8구간 확정', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '8구간 시각을 확정했습니다.' })).toBeVisible();
  await expect(panel.getByLabel('퇴장 끝', { exact: true })).toBeDisabled();
  saved = await (await page.request.get(`/api/cases/${item.case_id}`)).json();
  expect(saved.manifest.sessions[0].segments.confirmed).toBe(true);
  await page.setViewportSize({ width: 768, height: 1024 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
