import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';

test('M4: reviewer edits, stale narration, original frame and frozen downloads at 360px', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await page.getByLabel('계정', { exact: true }).fill('operator');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('button', { name: '로그아웃' })).toBeVisible();
  const headers = { 'X-KDOG-Request': '1' };
  let item = await (await page.request.post('/api/cases', { headers, data: { event_id: 'M4-BROWSER', participant_id: '0401', dog_name: '리포트 시험 가상견' } })).json();
  const base = `/api/cases/${item.case_id}`;
  const video = execFileSync('ffmpeg', ['-v', 'error', '-nostdin', '-f', 'lavfi', '-i', 'color=c=teal:s=320x240:d=4', '-c:v', 'libx264', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'], { windowsHide: true });
  item = await (await page.request.post(`${base}/videos`, { headers, data: video, params: { session_id: item.selected_session_id, camera_id: 'CAM-1', filename: 'synthetic-frame.mp4', expected_revision: item.input_revision } })).json();
  const started = await (await page.request.post(`${base}/analysis`, { headers, data: { expected_revision: item.input_revision } })).json();
  const runId = started.runs[0].run_id;
  const reportUrl = `${base}/reports/${runId}`;
  await expect.poll(async () => (await (await page.request.get(reportUrl)).json()).status).toBe('ready');
  const snapshot = await (await page.request.post('/api/exports', { headers, data: { format: 'xlsx', case_id: item.case_id, run_id: runId } })).json();
  await page.getByRole('button', { name: '로그아웃' }).click();
  await page.getByLabel('계정', { exact: true }).fill('reviewer');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await page.getByRole('button', { name: '0401 상세 열기' }).click();
  await expect(page.getByLabel('허용 선택지', { exact: true })).toBeVisible();
  await expect(page.getByLabel('리포트 미리보기', { exact: true })).toBeHidden();
  await page.getByLabel('허용 선택지', { exact: true }).selectOption({ index: 1 });
  await page.getByLabel('점수 수정 사유', { exact: true }).fill('원본 입장 장면 대조 후 수정');
  await page.getByRole('button', { name: '점수 수정 저장', exact: true }).click();
  await expect(page.getByText('저장했습니다.', { exact: true })).toBeVisible();
  const selectedRun = await page.getByLabel('관찰 실행 이력').inputValue();
  await page.getByRole('button', { name: '보고서', exact: true }).click();
  await expect(page.getByLabel('관찰 실행 이력')).toHaveValue(selectedRun);
  await expect(page.getByLabel('허용 선택지', { exact: true })).toBeHidden();
  await expect(page.getByRole('button', { name: '분석 시작', exact: true })).toHaveCount(0);
  await expect(page.getByText('설명 갱신 필요', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '현재 점수로 설명 생성·재시도', exact: true }).click();
  await expect(page.getByText('설명 준비됨', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '교육태도 (잠정)', exact: true })).toBeVisible();
  await expect(page.getByLabel('평가 범위', { exact: true })).toContainText('부분 평가 결과');
  await expect(page.getByLabel('평가 범위', { exact: true })).toContainText('미채점은 0점이 아닙니다.');
  await expect(page.getByRole('heading', { name: '영역 1', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '요약 근거 영상 1', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '원본 근거' })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByText('보고서 편집 도구', { exact: true }).click();
  await page.getByText('대표 이미지 선택', { exact: true }).click();
  const frameVideo = page.locator('.report-tools video');
  await frameVideo.evaluate(async (video: HTMLVideoElement) => { video.muted = true; await video.play(); });
  await page.getByRole('button', { name: '분석·검토', exact: true }).click();
  await expect.poll(() => frameVideo.evaluate((video: HTMLVideoElement) => video.paused)).toBe(true);
  await page.getByRole('button', { name: '보고서', exact: true }).click();
  await expect(page.getByLabel('원본 프레임 시간 (초)')).toHaveValue('1');
  await page.getByRole('button', { name: '대표 프레임 저장', exact: true }).click();
  await expect(page.getByRole('img', { name: '대표 프레임 · 원본 1.00초' })).toBeVisible();
  for (const close of await page.getByRole('button', { name: '알림 닫기' }).all()) await close.click();
  // A static navigation bar avoids covering the middle of a tall element capture.
  await page.locator('.section-nav').evaluate((element: HTMLElement) => { element.style.position = 'static'; });
  await page.locator('.report-preview').screenshot({ path: testInfo.outputPath('m4-report-desktop.png') });
  await page.getByText('보고서 편집 도구', { exact: true }).click();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('report-tab-desktop.png') });
  await page.setViewportSize({ width: 360, height: 800 });
  await page.locator('.report-preview').screenshot({ path: testInfo.outputPath('m4-report-mobile.png') });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('report-tab-mobile.png') });
  await page.locator('.section-nav').evaluate((element: HTMLElement) => element.style.removeProperty('position'));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByText('개별 파일 내보내기', { exact: true }).click();
  await page.getByRole('button', { name: '내보낼 대상 확인', exact: true }).click();
  await page.getByRole('button', { name: '현재 버전으로 파일 생성', exact: true }).click();
  const downloadLink = page.getByRole('link', { name: '파일 다운로드', exact: true });
  await expect(downloadLink).toBeVisible();
  const download = page.waitForEvent('download');
  await downloadLink.click();
  expect((await download).suggestedFilename()).toMatch(/\.pdf$/);
  expect((await page.request.post(`/api/exports/${snapshot.export_id}/generate`, { headers })).status()).toBe(200);
  const old = await page.request.get(`/api/exports/${snapshot.export_id}/file`);
  expect(old.status()).toBe(200);
  expect((await old.body()).subarray(0, 2).toString()).toBe('PK');
  const external = await page.context().browser()!.newContext({ baseURL: 'http://127.0.0.1:8765' });
  await external.request.post('/api/auth/login', { headers, data: { username: 'operator', password: 'Browser-test-only-42' } });
  item = await (await external.request.get(base)).json();
  expect((await external.request.post(`${base}/deletion`, { headers, data: { expected_revision: item.input_revision } })).status()).toBe(200);
  await expect(page.getByRole('img', { name: '대표 프레임 · 원본 1.00초' })).toHaveCount(0);
  await expect(page.getByLabel('리포트 미리보기', { exact: true })).toHaveCount(0);
  expect((await page.request.get(`/api/exports/${snapshot.export_id}/file`)).status()).toBe(403);
  await external.close();
  expect(errors).toEqual([]);
});

test('M4: developer report provider setting persists', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('계정', { exact: true }).fill('developer');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await page.getByLabel('설명 공급자', { exact: true }).selectOption('openai');
  await page.getByLabel('설명 모델 ID', { exact: true }).fill('synthetic-report-only');
  await page.getByRole('button', { name: '새 실행에 설명 설정 적용' }).click();
  await expect(page.getByText('새 실행에 설명 설정을 적용했습니다.')).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('설명 모델 ID', { exact: true })).toHaveValue('synthetic-report-only');
});
