import { test, expect } from '@playwright/test';

test('developer keys: register, test, revoke without leaking the secret; staff never see the panel', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await page.getByLabel('계정', { exact: true }).fill('developer');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  const panel = page.locator('.developer-settings');
  await expect(panel.getByRole('heading', { name: '공급자 키 관리' })).toBeVisible();
  await expect(panel.getByLabel('단계 프롬프트')).toHaveCount(0);
  await panel.getByLabel('키 공급자').selectOption('gemini');
  const secret = 'synthetic-browser-m5-not-a-real-key';
  await panel.getByLabel('새 API 키').fill(secret);
  await panel.getByRole('button', { name: '키 등록·교체', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '키를 보호하여 저장했습니다.' })).toBeVisible();
  await expect(panel.getByLabel('새 API 키')).toHaveValue('');
  await expect(panel.getByText('gemini · 등록됨', { exact: true })).toBeVisible();
  expect(await page.locator('body').innerText()).not.toContain(secret);
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain(secret);
  expect(await (await page.request.get('/api/developer/settings')).text()).not.toContain(secret);
  await page.route('**/api/developer/keys/gemini/test', route => route.fulfill({ json: { provider: 'gemini', reference: 'x', status: '연결 성공' } }));
  await panel.getByRole('button', { name: '키 연결 시험', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '연결 시험: 연결 성공' })).toBeVisible();
  await panel.getByRole('button', { name: '선택 공급자 키 폐기', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '키를 폐기했습니다.' })).toBeVisible();
  await panel.screenshot({ path: testInfo.outputPath('keys-desktop.png') });
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '로그아웃' }).click();
  await page.getByLabel('계정', { exact: true }).fill('operator');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('button', { name: '로그아웃' })).toBeVisible();
  await expect(page.getByLabel('새 API 키')).toHaveCount(0);
  expect((await page.request.get('/api/developer/settings')).status()).toBe(403);
  expect(errors).toEqual([]);
});
