import { test, expect } from '@playwright/test';

test('v3 survey: zero, exact labels, partial means and blank reasons', async ({ page }, testInfo) => {
  test.skip(process.env.KDOG_TEST_INTAKE_SPEC !== '20260929', 'Run with the current intake fixture.');
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('계정', { exact: true }).fill('operator');
  await page.getByLabel('비밀번호', { exact: true }).fill('Browser-test-only-42');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await page.getByLabel('행사 ID', { exact: true }).fill('V3');
  await page.getByLabel('참가자 ID', { exact: true }).fill('0009');
  await page.getByLabel('반려견 이름').fill('신판 합성견');
  await page.getByRole('button', { name: '참가자 저장' }).click();
  await expect(page.getByText('촬영 기준:', { exact: false })).toContainText('9월 29일');
  await page.getByRole('button', { name: '자료 가져오기', exact: true }).click();
  await page.getByRole('combobox', { name: '자료 종류' }).selectOption('survey');
  const ids = Array.from({ length: 28 }, (_, i) => `s${String(i + 1).padStart(2, '0')}`);
  const values = ids.map(id => id === 's07' ? '' : id === 's10' ? '0' : '3');
  await page.getByLabel('입력 파일', { exact: true }).setInputFiles({ name: 'survey-v3.csv', mimeType: 'text/csv',
    buffer: Buffer.from(`event_id,participant_id,survey_version,${ids.join(',')},s07_reason\nV3,0009,survey-20260929-v3,${values.join(',')},본 적 없음`) });
  await page.getByRole('button', { name: '검증 미리보기' }).click();
  await expect(page.getByText('검증 결과 · 정상 1행 / 오류 0행')).toBeVisible();
  await expect(page.getByText('설문 판본 survey-20260929-v3', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: '정상 1행 저장' }).click();
  await page.getByRole('button', { name: '설문', exact: true }).click();
  await expect(page.getByText('수치 응답 27/28', { exact: false })).toContainText('등록 완료 기준 Q04 미확정');
  await expect(page.getByText('응답 2/3 · 원본 완전응답 규칙: 모든 문항 응답 필요', { exact: true })).toBeVisible();
  await expect(page.getByText('25번 단독 응답', { exact: true })).toBeVisible();
  await page.getByText('설문 원응답', { exact: false }).click();
  await expect(page.locator('.survey-values p').filter({ has: page.locator('b', { hasText: /^10$/ }) }).locator('strong')).toHaveText('0');
  await expect(page.getByText('빈칸 사유: 본 적 없음', { exact: true })).toBeVisible();
  await expect(page.getByText('척도: 0 전혀없다', { exact: false }).first()).toBeVisible();
  await expect(page.locator('.survey-values p')).toHaveCount(28);
  await page.screenshot({ path: testInfo.outputPath('survey-v3.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: '자료 가져오기', exact: true }).click();
  await page.getByRole('combobox', { name: '자료 종류' }).selectOption('survey');
  await page.getByRole('combobox', { name: '입력 양식' }).selectOption('mapped');
  await expect(page.getByRole('button', { name: '검증 미리보기' })).toBeDisabled();
  await page.getByLabel('입력 파일', { exact: true }).setInputFiles({ name: 'old-source.csv', mimeType: 'text/csv', buffer: Buffer.from(`event_id,participant_id,${ids.join(',')}\nV3,0009,${values.join(',')}`) });
  await page.getByRole('combobox', { name: '원설문 판본 확인' }).selectOption('catalog-20260913-v2');
  await page.getByRole('button', { name: '연결할 열 불러오기' }).click();
  const oldCatalog = await (await page.request.get('/api/catalog/survey?version=catalog-20260913-v2')).json();
  const oldQuestion = oldCatalog.items.find((question: { item_id: string }) => question.item_id === 's12');
  await expect(page.getByText(`12번 · ${oldQuestion.text} (s12)`, { exact: false })).toBeVisible();
  expect(errors).toEqual([]);
});
